version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - htmlzip

build:
  os: ubuntu-20.04
  apt_packages:
    - graphviz
  tools:
    python: "3.8"
  jobs:
    post_install:
      - |
        wget https://julialang-s3.julialang.org/bin/linux/x64/1.6/julia-1.6.7-linux-x86_64.tar.gz
      - tar xzf julia-1.6.7-linux-x86_64.tar.gz
      - mkdir bin
      - ln -s $PWD/julia-1.6.7/bin/julia bin/julia
      - ./bin/julia docs/InstallIJulia.jl
      - pip install -e .[doc] -c .constraints/py3.8.txt
