name: compwa-org
channels:
  - conda-forge
dependencies:
  - graphviz # for binder
  - juliaup
  - pip
  - python==3.8.*
  - pip:
      - |
        -c .constraints/py3.8.txt
        -e .[dev]
variables:
  JULIAUP_CHANNEL: 1.6.7 # LTS
  PYTHONHASHSEED: 0
